config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'home#index'
  
  get 'home/index' #get 'home', to: 'home#index' tem exatamente o mesmo efeito

  resources :contents
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/content.rb
class Content < ApplicationRecord
  belongs_to :user

  validates :title, :description, presence: true

  has_many :tag_contents
  has_many :tags, through: :tag_contents
end

app/models/tag.rb
class Tag < ApplicationRecord
  belongs_to :user

  validates :name, presence: true, uniqueness: { scope: :user_id}

  has_many :tag_contents, dependent: :destroy

  has_many :contents, through: :tag_contents
end

app/models/tag_content.rb
class TagContent < ApplicationRecord
  belongs_to :tag
  belongs_to :content
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :tags
  has_many :contents
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :authenticate_user!
end

app/controllers/contents_controller.rb
class ContentsController < ApplicationController
    #skip_berore_action :authenticate_user!
    before_action :set_content, only: [:show, :edit, :update, :destroy]
    def index
      @contents = current_user.contents
    end

    def create
      @content = current_user.contents.build(content_params)

      # o maneira acime é uma forma abreviada de fazer
      # @content_params = Content.new(content_params)
      # @content.user = current_user
      # Isso é possível porque há uma relação no modelo entre User e Content

      if @content.save

        associate_tag
        
        redirect_to contents_path, notice: 'Conteudo criado com suceço!'
      else
        render :new
      end
    end

    def new
      @content = Content.new
    end

    def edit
    end
    
    def show
      @markdown = Redcarpet::Markdown.new(Redcarpet::Render::HTML, autolink: true, tables: true)
    end
    
    def update
      if @content.update(content_params)

        associate_tag

        redirect_to content_path, notice: 'Conteudo Atualizado con suceço'
      else
        render :edit
      end
    end

    def destroy
      @content.destroy
      redirect_to contents_path, notice: 'Conteudo deletado con suceço'
    end

    private

    def set_content
      @content = Content.find(params[:id])
    end

    def tags_params
      params.require(:content).permit(tags: [])[:tags].reject(&:blank?)
    end

    def content_params
      params.require(:content).permit(:title, :description)
    end

    def associate_tag
      tags = tags_params.map do | tag_name |
        current_user.tags.where(name: tag_name).first_or_initialize
      end

      @content.tags << tags
    end

  end
  

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/contents/_form.html.erb
<% if content.errors.any? %>
Errors: <%= content.errors.full_messages.join(', ')%> </br>
<% end %>

<%= form_with(model: @content, local: true) do | form | %>

    <div class="form-group">
        <div class="field">
            <%= form.label :title %>
            <%= form.text_field :title, class: 'form-control' %>
        </div>

        <div class="form-group">
            <%= form.label :description %>
            <%= form.text_area :description, class: 'form-control' %>
        </div>

        <div class="form-group">
            <%= form.label :tags %>
            <%= form.select :tags, options_for_select(current_user.tags.pluck(:name), content.tags.pluck(:name)), {}, { class: " form-control js-example-tokenizer", multiple: 'multiple'}%>
        </div>

        <div class="action">
            <%= form.submit 'Salvar', class: 'btn btn-primary'%>
        </div>    
    </div>

<% end %>

app/views/contents/edit.html.erb
<h1>Edit Content</h1>

<%= render 'form', content: @content %>

app/views/contents/index.html.erb
<h1>Contents</h1>

<%= form_tag(contents_path, method: :get) do %>
    <div class="form-group">
        <%= label_tag :tags %>
        <%= select_tag 'tags[]', options_for_select(current_user.tags.pluck(:name), params[:tags]), { class: "js-example-tokenizer form-control", multiple: 'multiple'}%>
    </div>

    <div class="action">
        <%= submit_tag 'SEARCH', class: 'btn btn-primary' %>
    </div>

    <br>
    <br>

<% end %>

<% @contents.each do | content | %>
    <%= link_to 'Show', content_path(content) %>
    <%= link_to 'Edit', edit_content_path(content) %>
    <%= link_to 'Delete', content_path(content), method: :delete, data: { confirm: 'Are you sure, you want to delete!'} %>
    <strong>Title:</strong> <%= content.title %><br>
    <strong>Description: </strong> <%= content.description %> </br>
    <strong>Tags:</strong> <%= content.tags.pluck(:name).join(', ')%>
 


 </br>
 </br>
<% end %>

app/views/contents/new.html.erb
<h1> Novo Conteudo </h1>

<%= render 'form', content: @content %>

app/views/contents/show.html.erb
<h1>Contents</h1>


    Title: <%= @content.title %><br>
    Description: <%= raw(@markdown.render( @content.description )) %> </br>
 <%= link_to 'Edit', edit_content_path(@content) %>
 <%= link_to 'Back', contents_path %>

 </br>
 </br>

app/views/home/index.html.erb
<h1>Cloud Tags</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MindApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <div class="container">
      <% if user_signed_in? %>
         <%= link_to 'Logout', destroy_user_session_path  , method: :delete %>
      <% end %>
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
    
    <%= yield %>
    </div>

  </body>
</html>